### PR TITLE
Better mouse and touch events management

### PR DESCRIPTION
**Pull request by fpluquet**
Moving avatar can be done from outside from the image.
Moving avatar can be done by touch events.

### CODE REVIEW

**Comment by fpluquet** [comment]
I added also the rotation feature.

**Comment by fpluquet** [comment]
Can you accept this pull request ? Or add me as administrator of this repository ?

**Comment by AlecTroemel** [comment]
hi @fpluquet, thanks for the PR and sorry about the delay. I'll review it and try to get it merged

**Comment by AlecTroemel** [comment]
@fpluquet, this repo is no longer used/maintained by mirusresearch. If its ok with you we can transfer ownership of it to you

**Comment by fpluquet** [comment]
It's ok for me. Tks.

**Comment by AlecTroemel** [comment]
@fpluquet since you've already forked this repo, github wont let me "transfer" this one. I can have the docs point to your fork. Or the other option would be for you to delete your fork, then I can transfer

**Comment by fpluquet** [comment]
I can delete my fork. But it's perhaps better you merge this PR before I delete my fork, no ?

**Comment by fpluquet** [comment]
Tks. I deleted my fork. Can you transfer this one to me ?

**Pull request merged**
